services:
  - type: web
    name: chat-api
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        sync: false

  - type: worker
    name: chat-subscriber
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: node worker.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        sync: false
